apiVersion: v1
kind: Pod
metadata:
  name: echowik-step2
  namespace: tp4
  labels:
    step: "2"
spec:
  containers:
    - name: echowik-step2
      image: registry.cluster.wik.cloud/public/echo
      ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: echowik-step2
  namespace: tp4
spec:
  replicas: 4
  selector:
    matchLabels:
      step: "2"
  template:
    metadata:
      labels:
       step: "2"
    spec:
      containers:
        - name: echowik-step2
          image: registry.cluster.wik.cloud/public/echo
          ports:
          - containerPort: 8080