apiVersion: v1
kind: Pod
metadata:
  name: echowik-step3
  namespace: tp4
  labels:
    step: "3"
spec:
  containers:
    - name: echowik-step3
      image: registry.cluster.wik.cloud/public/echo
      ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echowik-step3
  namespace: tp4
  labels:
    step: "3"
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
  selector:
    matchLabels:
      step: "3"
  template:
    metadata:
      labels:
       step: "3"
    spec:
      containers:
        - name: echowik-step3
          image: registry.cluster.wik.cloud/public/echo
          ports:
          - containerPort: 8080